" ------------------------------ VUNDLE ------------------------------
"
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'



" ------------------------------ PLUGINS ------------------------------
" C++ syntax highlighting
Plugin 'octol/vim-cpp-enhanced-highlight'
" NERDTree
Plugin 'scrooloose/nerdtree'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

" ------------------------------ STARTUP ------------------------------

" Identation settings
set tabstop=4           " Tab whitespace equivalents.
set shiftwidth=4	" Indenting is 4 whitespaces.
set softtabstop=4       " Tab and backspace keypresses remove 4 whitespaces.
set noexpandtab		" Turn off convertion of tabs into whitespaces.
set noautoindent	" Turn off auto indentation.
set smartindent	        " Turn off smart indentation.
set nocindent		" Turn off C program specific rules.
filetype indent off
filetype plugin indent off

" Line numbering
set number

" Text width
set textwidth=80

" Stop auto commenting
autocmd BufNewFile,BufRead * setlocal formatoptions-=cro

" NERDTree
au VimEnter *  NERDTree



" ------------------------------ CPP Enhanced Highlight ------------------------------
let g:cpp_class_scope_highlight = 1
let g:cpp_member_variable_highlight = 1
let g:cpp_class_decl_highlight = 1
let g:cpp_posix_standard = 1
