" ------------------------------ VUNDLE ------------------------------
"
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'



" ------------------------------ PLUGINS ------------------------------
" C++ syntax highlighting
Plugin 'octol/vim-cpp-enhanced-highlight'
" NERDTree
Plugin 'scrooloose/nerdtree'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

 

" ------------------------------ STARTUP ------------------------------
" Tab stop
set ts=4

" Set
set sts=4

" Expand tabs to spaces
"set et

" Shift width
set shiftwidth=0

" Line numbering
set number

" Text width
set textwidth=80

" Stop auto indent
set noautoindent

" Set smart indent
set smartindent
set nocindent
set indentexpr=
filetype indent off
filetype plugin indent off

" Stop auto commenting
autocmd BufNewFile,BufRead * setlocal formatoptions-=cro

" NERDTree
au VimEnter *  NERDTree



" ------------------------------ CPP Enhanced Highlight ------------------------------
let g:cpp_class_scope_highlight = 1
let g:cpp_member_variable_highlight = 1
let g:cpp_class_decl_highlight = 1
let g:cpp_posix_standard = 1
