" ---- Vundle -----------------------------------------------------------------

set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" ---- Plugins ----------------------------------------------------------------

Plugin 'octol/vim-cpp-enhanced-highlight'
Plugin 'preservim/nerdtree'
Plugin 'rhysd/vim-clang-format'

call vundle#end()                          " required

" ---- VIM config -------------------------------------------------------------

filetype plugin indent on                  " Activate filetype plugins
syntax enable                              " Activate syntax

colo ron                                   " Set colorscheme

set tabstop=4                              " Tab is 4 whitespace coloumns
set shiftwidth=4                           " Indenting is 4 whitespaces
set softtabstop=4                          " Backspace removes 4 whitespaces
set expandtab                              " Convert tabs into whitespaces
set autoindent                             " Auto indentation
set smartindent                            " Smart indentation
set nocindent                              " C program specific indentation
filetype indent off                        " Filetype-based indentation
filetype indent plugin off                 " Filetype-based indentation

set cursorline                             " Activate cursor line
set number                                 " Line numbering
set textwidth=80                           " Text width
set wrap                                   " Text wrapping
set completeopt=longest,menuone,preview    " Enhanced completion menu
set wildmenu                               " Enhanced completion menu
set hlsearch                               " Highlight searches
set incsearch                              " Incrementally search words
set showcmd                                " Show command line in the last line
set ruler                                  " Show line and column of cursor
set splitbelow                             " Splits below current window

" Do not show numbers when a terminal is opened.
autocmd TerminalOpen * set nonu

" Stop auto commenting
autocmd BufNewFile,BufRead * setlocal formatoptions-=cro

" Copy and paste to clipboard (?).
set clipboard=unnamedplus

" ---- NERDTree ---------------------------------------------------------------

autocmd VimEnter * NERDTree

let g:NERDTreeNodeDelimiter = "\u00a0"

" ---- Cpp Enhanced Highlight -------------------------------------------------

let g:cpp_class_scope_highlight = 1
let g:cpp_member_variable_highlight = 1
let g:cpp_class_decl_highlight = 1
let g:cpp_posix_standard = 1
let g:cpp_concepts_highlight = 1
let g:cpp_member_variable_highlight = 0
let g:cpp_no_function_highlight = 1
